### ISSUE TITLE
Merge Sort in Java (HacktoberFest 2021)

### ISSUE THREAD

**Issue by shecoderfinally** [shecoderfinally/Sorting-and-Searching-Techniques#1]
Feel Free to submit PR for Merge Sort in Java

**Comment by Onkar627** [comment]
@shecoderfinally I would like to work on this issue.

**Comment by shecoderfinally** [comment]
He

> @shecoderfinally I would like to work on this issue.

Hey @Onkar627 someone has already made their submission in Merge Sort in Java Language..So try improving that code or make your submission for merge sort in another language..
There are several other Sorting and Searching Techniques you could contribute to..
Happy Coding :)
