### ISSUE TITLE
Max of 2 numbers in Java( HacktoberFest 2021)

### ISSUE THREAD

**Issue by shecoderfinally** [shecoderfinally/Sorting-and-Searching-Techniques#14]
Max of 2 numbers

**Comment by Khushbu2411** [comment]
I want to work in this issue . if you can assign it to me.

**Comment by Abhicoder03** [comment]
Please assign me this issue under hacktoberfest

**Comment by ajinkyabodke** [comment]
i would like to work on this issue and complete it at the earliest,please assign it to me
