### ISSUE TITLE
Reverse a String in Java(HacktoberFest 2021)

### ISSUE THREAD

**Issue by shecoderfinally** [shecoderfinally/Sorting-and-Searching-Techniques#15]
Reverse a String in Java

**Comment by ajinkyabodke** [comment]
i would like to work on this issue and complete it at the earliest,please assign it to me

**Comment by Khushbu2411** [comment]
I would like to work in this issue

**Comment by shecoderfinally** [comment]
@ajinkyabodke @Khushbu2411 assigned to both of you..please make the contribution at the earliest..

**Comment by yashguptaji** [comment]
Can I work on it?

**Comment by shecoderfinally** [comment]
Yes sure

**Comment by ajinkyabodke** [comment]
> @ajinkyabodke @Khushbu2411 assigned to both of you..please make the contribution at the earliest..

@shecoderfinally submitted the pr,please check and merge it

**Comment by yashguptaji** [comment]
@shecoderfinally submitted PR #25 . Pls check. Thanks

**Comment by vinitvins** [comment]
Can you assign me this issue?
