### ISSUE TITLE
Max of 2 numbers in C( HacktoberFest 2021)

### ISSUE THREAD

**Issue by shecoderfinally** [shecoderfinally/Sorting-and-Searching-Techniques#16]
Max of 2 numbers in C

**Comment by ajinkyabodke** [comment]
i would like to work on this issue and complete it at the earliest,please assign it to me

**Comment by Abhicoder03** [comment]
Please assign me this issue under hacktoberfest

**Comment by shecoderfinally** [comment]
@ajinkyabodke @Abhicoder03 assigned it to both of you..please make the contribution at earliest..

**Comment by Abhicoder03** [comment]
okay thanks @shecoderfinally

**Comment by ajinkyabodke** [comment]
> @ajinkyabodke @Abhicoder03 assigned it to both of you..please make the contribution at earliest..

@shecoderfinally submitted the pr,please check and merge it

**Comment by shecoderfinally** [comment]
> > @ajinkyabodke @Abhicoder03 assigned it to both of you..please make the contribution at earliest..
> 
> @shecoderfinally submitted the pr,please check and merge it

Done

**Comment by ajinkyabodke** [comment]
> > > @ajinkyabodke @Abhicoder03 assigned it to both of you..please make the contribution at earliest..
> > 
> > 
> > @shecoderfinally submitted the pr,please check and merge it
> 
> Done

thanks

**Comment by Abhicoder03** [comment]
@shecoderfinally done. Please merge it.

**Comment by shecoderfinally** [comment]
> @shecoderfinally done. Please merge it.

Done
