### ISSUE TITLE
Codechef Problems

### ISSUE THREAD

**Issue by Abhicoder03** [shecoderfinally/Sorting-and-Searching-Techniques#166]
Should i create a folder where we can contribute codechef problems solution.
It would beneficial for coders whenver they are in trouble in codechef.

Could you please assign me this issue. @shecoderfinally

**Comment by shecoderfinally** [comment]
> Should i create a folder where we can contribute codechef problems solution. It would beneficial for coders whenver they are in trouble in codechef.
> 
> Could you please assign me this issue. @shecoderfinally

Yes I already have assigned the same issue you requested earlier today..

**Comment by Abhicoder03** [comment]
Why you closed an issue and then assign? 
Should i just make a PR?
@shecoderfinally
