### ISSUE TITLE
Reverse string using recursion

### ISSUE THREAD

**Issue by Khushi-agarwal** [shecoderfinally/Sorting-and-Searching-Techniques#216]
I want to add the code of reverse string in recursion folder in c++. @shecoderfinally please assign me this issue.

**Comment by Manas0916** [comment]
Hey! I want to  Solve the problem in JAVA . Can you Assign this to me!

**Comment by ashan-tharaka** [comment]
@shecoderfinally hai!! i want to solve the problem using Java .can you assign this to me?

**Comment by shecoderfinally** [comment]
> I want to add the code of reverse string in recursion folder in c++. @shecoderfinally please assign me this issue.

Yes sure @Khushi-agarwal..Assigned this issue to you..please make the contribution at the earliest...

**Comment by shecoderfinally** [comment]
> Hey! I want to Solve the problem in JAVA . Can you Assign this to me!

@Manas0916 yes sure..assigned the issue to you for Java..Please make the contribution at the earliest

**Comment by shecoderfinally** [comment]
> @shecoderfinally hai!! i want to solve the problem using Java .can you assign this to me?

Hey @ashan-tharaka this issue is already assigned for Java, C++..Feel free to make the contribution in another language

**Comment by hackgone** [comment]
can i do it with help of python?

**Comment by bidishaMondal7** [comment]
Hey, I want to try it in Ruby, can you please  assign it to me @shecoderfinally .
