### ISSUE TITLE
Binary Search in C++

### ISSUE THREAD

**Issue by Abhicoder03** [shecoderfinally/Sorting-and-Searching-Techniques#29]
Could you please assign me.

**Comment by shecoderfinally** [comment]
> Could you please assign me.

Yupp done

**Comment by Abhicoder03** [comment]
@shecoderfinally Please add hacktoberfest label also.

**Comment by SrishtiArya07** [comment]
@shecoderfinally  can I work on this issue in python?

**Comment by yashguptaji** [comment]
Pls assign me
