### ISSUE TITLE
GCD AND LCM IN C++

### ISSUE THREAD

**Issue by Abhicoder03** [shecoderfinally/Sorting-and-Searching-Techniques#31]
Could you please assign this to me.

**Comment by yashguptaji** [comment]
assign me pls

**Comment by Abhicoder03** [comment]
@shecoderfinally

**Comment by ajinkyabodke** [comment]
@shecoderfinally added pr please check and merge it

**Comment by Abhicoder03** [comment]
@shecoderfinally Added.

**Comment by shreyas1925** [comment]
@shecoderfinally  added pr please check and merge for java
