### ISSUE TITLE
Calculator in Java (Hacktoberfest2021)

### ISSUE THREAD

**Issue by shecoderfinally** [shecoderfinally/Sorting-and-Searching-Techniques#48]
Calculator in Java

**Comment by vikhyat-github** [comment]
@shecoderfinally Can you assign this to me
I am interested in contributing.
Also mention the features you want me to include.

**Comment by shecoderfinally** [comment]
Hey @vikhyat-github,
Ill assign it to you..
Please add all the basic Arithmetic Features.(+,-,*,/,%)

**Comment by vikhyat-github** [comment]
I have made a PR.

**Comment by Kanai2003** [comment]
I am interested to do this and fixed it.
