### ISSUE TITLE
Codeforces Problems

### ISSUE THREAD

**Issue by Abhicoder03** [shecoderfinally/Sorting-and-Searching-Techniques#77]
Should I make a folder for codeforces solutions?
It would be really helpful for cp beginners.
Could you please assign me this issue.
@shecoderfinally

**Comment by shecoderfinally** [comment]
Yes thats a great idea @Abhicoder03

**Comment by Abhicoder03** [comment]
Why you closed the issue @shecoderfinally ?

**Comment by Abhicoder03** [comment]
Why you closed the issue?
