### ISSUE TITLE
Linear Search in C (HacktoberFest2021)

### ISSUE THREAD

**Issue by shecoderfinally** [shecoderfinally/Sorting-and-Searching-Techniques#9]
Linear Search in C

**Comment by Recognizeyourself** [comment]
Can i work on it ? Kindly Assign this to me.

**Comment by swapnil604** [comment]
@shecoderfinally please assign I'd love to contribute.

**Comment by shecoderfinally** [comment]
> @shecoderfinally please assign I'd love to contribute.

Hey @swapnil604 ,
Yes sure..Assigned it to you..Go ahead and make the contribution..

**Comment by shecoderfinally** [comment]
> Can i work on it ? Kindly Assign this to me.

Hey @Recognizeyourself  ,
Yes sure..Assigned it to you..Go ahead and make the contribution..

**Comment by shecoderfinally** [comment]
> @shecoderfinally please assign I'd love to contribute.

Hey @swapnil604,
Yes sure..Please make the contribution in another language like C,Python..

**Comment by Recognizeyourself** [comment]
> > Can i work on it ? Kindly Assign this to me.
> 
> Hey @Recognizeyourself , Yes sure..Assigned it to you..Go ahead and make the contribution in Java..

Thankyou !!

**Comment by swapnil604** [comment]
Sure, will do in python.

**Comment by AmanRana10** [comment]
@shecoderfinally can i work on this , i can code it in c++?

**Comment by shecoderfinally** [comment]
> @shecoderfinally can i work on this , i can code it in c++?

Yes sure..Ill assign it to you..

**Comment by SrishtiArya07** [comment]
@shecoderfinally Can I please work on this issue in cpp?
