### ISSUE TITLE
CountingSort in C(Hacktoberfest2021)

### ISSUE THREAD

**Issue by shecoderfinally** [shecoderfinally/Sorting-and-Searching-Techniques#93]
CountingSort in C

**Comment by divya1467** [comment]
can you please assign this to me!

**Comment by Abhicoder03** [comment]
@shecoderfinally Please assign this to me.

**Comment by shecoderfinally** [comment]
> can you please assign this to me!

Assigned..please make contribution at earliest..

**Comment by shecoderfinally** [comment]
> @shecoderfinally Please assign this to me.

Already assigned..Please make new contribution

**Comment by divya1467** [comment]
> > can you please assign this to me!
> 
> Assigned..please make contribution at earliest..

sure!
