### ISSUE TITLE
CountingSort in C++(Hacktoberfest2021)

### ISSUE THREAD

**Issue by shecoderfinally** [shecoderfinally/Sorting-and-Searching-Techniques#96]
CountingSort in C++

**Comment by palash9561** [comment]
can you assign this to me

**Comment by rohith1125** [comment]
@shecoderfinally Can you assign me ? I can Code it

**Comment by palash9561** [comment]
I did it please merged it

**Comment by shecoderfinally** [comment]
> I did it please merged it

Yes merged

**Comment by shecoderfinally** [comment]
> @shecoderfinally Can you assign me ? I can Code it

Try in a different language..in C++its done
